<?php /** @var \Magento\Backend\Block\Template $block */ ?>
<style type='text/css'>
    .widget_group_label {
        margin: 0;
        font-size: 1.7rem;
        display: block;
        line-height: 1em;
        font-weight: 600;
        letter-spacing: .025em;
        padding-bottom: 1.9rem;
        border-bottom: 1px solid #cccccc;
    }
</style>
<h1 class="widget_group_label"><?= $block->getData('label') ?></h1>